### ISSUE TITLE
Are there plans to engage WHO and the governments to adopt this solution? Any plans to integrate with blockchain to make it tamper proof?

### ISSUE THREAD

**Issue by nathanawmk** [svee/immunity-passport#1]
Are there plans to engage WHO and the governments to adopt this solution? Any plans to integrate with blockchain to make it tamper proof?

**Comment by svee** [comment]
blockchain seems like a useful enhancement not thought of that. 

It is one single person development don't have reach/bandwidth for engaging with governments at this stage.  Assuming that solution is simple enough that governments will have their own applications.  Glad if this helps someone to get started.
